### ISSUE TITLE
В заметках пользователя присутствует лог пользователей

### ISSUE THREAD

**Issue by SiavaRu** [AlexSheer/phpbb3.1-Connection-Log#1]
Подробности тут:
http://www.phpbbguru.net/community/viewtopic.php?f=64&t=43557&p=488731#p488731

**Comment by AlexSheer** [comment]
Fixed! https://github.com/AlexSheer/phpbb3.1-Connection-Log/commit/b2a0795744dd20c70708dcbce356f9c2c7a97a2a
